### ISSUE TITLE
Describe OnEventChanged notification

### ISSUE THREAD

**Issue by AnastasiyaBritanova** [smartdevicelink/sdl_hmi_integration_guidelines#19] opened 2016-09-22 09:23 UTC
New `OnEventChanged` notification replaces `OnEmergencyEvent, OnDeactivateHMI, OnPhoneCall` + introduces new events `AUDIO_SOURCE, EMBEDDED_NAVI`.
The above needs to be properly described in Guidelines.

also discussed here: smartdevicelink/sdl_core/issues/831

**Comment by AnastasiyaBritanova** [comment] 2016-09-23 14:10
![oneventchanged deactivate_hmi](https://cloud.githubusercontent.com/assets/11644716/18788725/abbc6b44-81b0-11e6-8fdd-90bcde714ec9.png)
![oneventchanged emergency_event](https://cloud.githubusercontent.com/assets/11644716/18788726/abbd58b0-81b0-11e6-999b-9d12c54908dc.png)
![oneventchanged phone_call](https://cloud.githubusercontent.com/assets/11644716/18788727/abc2377c-81b0-11e6-9e42-f9abf132000a.png)

**Comment by jacobkeeler** [comment] 2018-10-24 18:28
Duplicate of #82

**Closed by jacobkeeler** 2018-10-24 18:28 UTC
Labels: enhancement
